version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static

  db:
    image: postgres:15
    container_name: restaurant_postgre_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1013108226
      POSTGRES_DB: restaurant_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  static_volume:
  redis_data:
