version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static

  db:
    image: postgres:15
    container_name: restaurant_postgre_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1013108226
      POSTGRES_DB: restaurant_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  webhook_tunnel:
    image: webhookrelay/webhookrelayd:latest
    container_name: webhook_tunnel
    environment:
      - HTTP_PROXY=http://192.168.49.1:8282
      - HTTPS_PROXY=http://192.168.49.1:8282
      - NO_PROXY=localhost,127.0.0.1
    command: --mode tunnel -k 9c38dcce-5e7f-418e-bf51-a83ae063d9e1 -s sr2ypJqdP74c -t restaurantsystem
    network_mode: host

  webhook_bucket:
    image: webhookrelay/webhookrelayd:latest
    container_name: webhook_bucket
    environment:
      - HTTP_PROXY=http://192.168.49.1:8282
      - HTTPS_PROXY=http://192.168.49.1:8282
      - NO_PROXY=host.docker.internal
    command: -k 3b1086d2-a860-46ef-88dd-7a2ea878ee43 -s gcxLIkRdXO3A -b restaurantone
    network_mode: host

volumes:
  postgres_data:
  static_volume:
  redis_data:
