# Generated by Django 5.0.4 on 2025-01-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
