# Generated by Django 5.0.4 on 2025-11-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_free_quantity', models.PositiveIntegerField(default=0)),
                ('is_optional', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='menu.menuitem')),
            ],
        ),
    ]
