# Generated by Django 5.0.4 on 2025-02-06 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.orderstatus'),
        ),
    ]
