# Generated by Django 5.0.4 on 2025-02-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_gateway_id', models.CharField(null=True, unique=True)),
                ('transaction_id', models.CharField(max_length=150, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'FALLIDO')], default='pendiente', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='orders.order')),
            ],
            options={
                'db_table': 'payment_orders',
            },
        ),
    ]
