# Generated by Django 5.0.4 on 2025-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_gateway_id',
            field=models.CharField(unique=True),
        ),
    ]
