# Generated by Django 5.0.4 on 2025-02-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_paymentorder_order_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_gateway_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
