# Generated by Django 5.0.4 on 2025-02-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_paymentorder_order_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'FALLIDO'), ('CANCELADO', 'Cancelado')], default='pendiente', max_length=10),
        ),
    ]
